AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple SAM template for AI Accounting Agent backend

Parameters:
  BedrockModelId:
    Type: String
    Description: Bedrock model id to use for inference
  UploadBucketName:
    Type: String
    Description: S3 bucket name to store uploads

Resources:
  ChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-accounting-chat
      Runtime: python3.9
      Handler: backend.handler.lambda_handler
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          BEDROCK_MODEL_ID: !Ref BedrockModelId
          UPLOAD_BUCKET: !Ref UploadBucketName
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref UploadBucketName
      Events:
        ChatApi:
          Type: Api
          Properties:
            Path: /chat
            Method: post
        PresignApi:
          Type: Api
          Properties:
            Path: /presign
            Method: post

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
